export const AuthErrorMessages = {
  EMAIL_ALREADY_EXISTS: 'AUTH_EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  NAME_REQUIRED: 'NAME_REQUIRED',
  INVALID_EMAIL_FORMAT: 'INVALID_EMAIL_FORMAT',
  OTP_EXPIRED: 'OTP_EXPIRED',
  INVALID_OTP: 'INVALID_OTP',
  OTP_TOO_MANY_ATTEMPTS: 'OTP_TOO_MANY_ATTEMPTS',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  If_email_exists_OTP_sent: 'If_email_exists_OTP_sent',
  INVALID_REQUEST: 'INVALID_REQUEST',
} as const;

export type AuthErrorCodeType = typeof AuthErrorMessages[keyof typeof AuthErrorMessages];
