export const EnvErrorMessages = {
  INVALID_ENV: 'ENV_INVALID_CONFIGURATION',

  DATABASE_URL_REQUIRED: 'ENV_DATABASE_URL_REQUIRED',
  JWT_SECRET_SHORT: 'ENV_JWT_SECRET_TOO_SHORT_MIN_10',
  JWT_REFRESH_SECRET_SHORT: 'ENV_JWT_REFRESH_SECRET_TOO_SHORT_MIN_10',
  REDIS_URL_REQUIRED: 'ENV_REDIS_URL_REQUIRED',
} as const;