export const EnvErrorMessages = {
  DATABASE_URL_REQUIRED: 'ENV_DATABASE_URL_REQUIRED',
  JWT_SECRET_SHORT: 'ENV_JWT_SECRET_TOO_SHORT_MIN_10',
  JWT_REFRESH_SECRET_SHORT: 'ENV_JWT_REFRESH_SECRET_TOO_SHORT_MIN_10',
  REDIS_URL_REQUIRED: 'ENV_REDIS_URL_REQUIRED',

  DATABASE_UNAVAILABLE: 'SERVER_DATABASE_UNAVAILABLE',
  DATABASE_TIMEOUT: 'SERVER_DATABASE_BUSY',
  INTERNAL_SERVER_ERROR: 'SERVER_INTERNAL_ERROR',
  INVALID_ENV: "ENV_INVALID_CONFIGURATION"
} as const;