export const EnvErrorMessages = {
  INVALID_ENV: 'INVALID_ENV_CONFIGURATION',
  DATABASE_URL_REQUIRED: 'DATABASE_URL_REQUIRED',
  JWT_SECRET_SHORT: 'JWT_SECRET_TOO_SHORT',
  JWT_REFRESH_SECRET_SHORT: 'JWT_REFRESH_SECRET_TOO_SHORT',
  REDIS_URL_REQUIRED: 'REDIS_URL_REQUIRED',
} as const;
