export const MovieErrorMessages = {
  MOVIE_NOT_FOUND: 'MOVIE_NOT_FOUND',
  TITLE_REQUIRED: 'TITLE_REQUIRED',
  INVALID_PRICE: 'INVALID_PRICE',
  PREMIERE_DATE_REQUIRED: 'PREMIERE_DATE_REQUIRED',
} as const;
