export const SubscriptionErrorMessages = {
  ALREADY_SUBSCRIBED: 'SUBSCRIPTION_ALREADY_ACTIVE',
  NO_ACTIVE_SUBSCRIPTION: 'SUBSCRIPTION_NOT_ACTIVE',
  SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND',
  INVALID_PLAN: 'SUBSCRIPTION_INVALID_PLAN',
} as const;
