export const TicketErrorMessages = {
  MOVIE_NOT_FOUND: 'TICKET_MOVIE_NOT_FOUND',
  ALREADY_PURCHASED: 'TICKET_ALREADY_PURCHASED',
  TICKET_NOT_FOUND: 'TICKET_NOT_FOUND',
  NO_ACCESS: 'TICKET_NO_ACCESS_TO_CONTENT',
} as const;
